name: Desplegar SAM 3 a GitHub Registry

on:
  push:
    branches:
      - main  # O 'master' si esa es tu rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    # Estos permisos dejan que GitHub guarde el contenedor en tu propia cuenta
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Iniciar sesión en el almacén de GitHub (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Esto es automático, no lo tienes que crear

      - name: Construir y Subir imagen
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Esto guarda la imagen con tu nombre de usuario de GitHub
          tags: ghcr.io/${{ github.repository_owner }}/sam3-runpod:latest
          # Aquí le pasamos tu token de Hugging Face al Dockerfile
          build-args: |
            HF_TOKEN=${{ secrets.HF_TOKEN }}
